version: "3.9"

x-aws-config: &aws-config 
  DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: "local"
  AWS_SECRET_ACCESS_KEY: "local"


services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    environment:
      AWS_REGION: "eu-central-1"
    ports:
      - "8000:8000"

  web:
    build: .
    env_file:
      - .env
    environment:
      RUN_IN_DOCKER: "true"
      AES_ENCRYPTION_SECRET: "abc&1*~#^2^#s0^=)^^7%b34"
      <<: *aws-config
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    profiles:
      - local-lambda

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      <<: *aws-config
    depends_on:
      - dynamodb-local
