// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ContactInfoInput struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Subject string `json:"subject"`
	Message string `json:"message"`
}

type CreateGuestbookEntryInput struct {
	Email   string  `json:"email"`
	Message string  `json:"message"`
	Name    string  `json:"name"`
	Company *string `json:"company"`
}

type GetGuestbookOutput struct {
	Entries []*GuestbookEntry `json:"entries"`
	Cursor  *string           `json:"cursor"`
}

type GuestbookEntry struct {
	Email     string  `json:"email"`
	Message   string  `json:"message"`
	Name      string  `json:"name"`
	Company   *string `json:"company"`
	CreatedAt string  `json:"createdAt"`
}
